pacman-rainbow:
    env: pacman
    run: DQN
    local_dir: out
    config:
        num_atoms: 51
        noisy: True
        gamma: 0.95
        lr: .0001
        hiddens: [512]
        learning_starts: 10000
        buffer_size: 50000
        sample_batch_size: 4
        train_batch_size: 32
        schedule_max_timesteps: 2000000
        exploration_final_eps: 0.0
        exploration_fraction: .000001
        target_network_update_freq: 500
        prioritized_replay: True
        prioritized_replay_alpha: 0.5
        beta_annealing_fraction: 0.2
        final_prioritized_replay_beta: 1.0
        n_step: 3
        num_gpus: 1
        #num_cpus_per_worker: 1
        #num_workers: 3
        model:
            custom_model: 'PacmanModel'
            custom_preprocessor: null
            framestack: False
            #conv_filters: [[16, [4, 4], 1], [32, [4, 4], 1], [256, [11, 11], 1]]
